### ISSUE TITLE
error loading state_dict

### ISSUE THREAD

**Issue by Aradhya0510** [simaiden/Clothes-Detection-MA5204#5]
the model architecture in config file and the weight file seems to have different shape.
I am getting this error:
size mismatch for roi_heads.box.predictor.cls_score.weight: copying a param with shape torch.Size([14, 1024]) from checkpoint, the shape in current model is torch.Size([81, 1024]).
size mismatch for roi_heads.box.predictor.cls_score.bias: copying a param with shape torch.Size([14]) from checkpoint, the shape in current model is torch.Size([81]).
size mismatch for roi_heads.box.predictor.bbox_pred.weight: copying a param with shape torch.Size([56, 1024]) from checkpoint, the shape in current model is torch.Size([324, 1024]).
size mismatch for roi_heads.box.predictor.bbox_pred.bias: copying a param with shape torch.Size([56]) from checkpoint, the shape in current model is torch.Size([324]).

**Comment by simaiden** [comment]
I guess you are using the maskrcnn-benchmark models? In that case change this [value](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/config/defaults.py#L217) to 14 . Also you can add to the specific config file like:

```
MODEL:
   ROI_BOX_HEAD:
      NUM_CLASSES = 14
```

In RetinaNet, change this [value](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/config/defaults.py#L217)
